# Generated by Django 3.1.2 on 2020-12-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Описание ачивки'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Доп описание ответа'),
        ),
        migrations.AlterField(
            model_name='division',
            name='description',
            field=models.TextField(verbose_name='Описание подразделения сотрудников'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='description',
            field=models.TextField(verbose_name='Описание трудовых обязанностей'),
        ),
        migrations.AlterField(
            model_name='mainquest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вопроса'),
        ),
        migrations.AlterField(
            model_name='questiontheme',
            name='description',
            field=models.TextField(verbose_name='Описание тематики'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание задания'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(verbose_name='Описание команды'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(verbose_name='Описание теста'),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='description',
            field=models.TextField(verbose_name='Описание задания'),
        ),
    ]
