# Generated by Django 3.1.2 on 2021-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201211_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='testblock',
            name='questions',
            field=models.ManyToManyField(default=None, to='api.Question', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='status',
            field=models.CharField(choices=[('started', 'Начат'), ('failed', 'Провален'), ('done', 'Выполнен')], default='started', max_length=20, verbose_name='Статус'),
        ),
    ]
