const state = {
    isLoading: true,
    individualRaiting: [
        {
            id: 1,
            img: require('@/mocks/woman.png'),
            name: 'Александра Пушкина',
            description: 'ВКЦ 2',
            raitingValue: 5.0,
            ratingDay: 4,
            ratingWeek: 5,
            ratingMonth: 4,
        },
        {
            id: 2,
            img: require('@/mocks/woman.png'),
            name: 'Александра Пушкина',
            description: 'ВКЦ 2',
            raitingValue: 5.0,
            ratingDay: 4,
            ratingWeek: 3,
            ratingMonth: 4,
        },
        {
            id: 3,
            img: require('@/mocks/woman.png'),
            name: 'Александра Пушкина',
            description: 'ВКЦ 2',
            raitingValue: 5.0,
            ratingDay: 3,
            ratingWeek: 5,
            ratingMonth: 4,
        },
        {
            id: 4,
            img: require('@/mocks/woman.png'),
            name: 'Александра Пушкина',
            description: 'ВКЦ 2',
            raitingValue: 4.9,
            ratingDay: 4,
            ratingWeek: 2,
            ratingMonth: 4,
        },
        {
            id: 5,
            img: require('@/mocks/woman.png'),
            name: 'Александра Пушкина',
            description: 'ВКЦ 2',
            raitingValue: 5.0,
            ratingDay: 2,
            ratingWeek: 5,
            ratingMonth: 4,
        },
        {
            id: 6,
            img: require('@/mocks/woman.png'),
            name: 'Александра Пушкина',
            description: 'ВКЦ 2',
            raitingValue: 5.0,
            ratingDay: 4,
            ratingWeek: 5,
            ratingMonth: 4,
        },
    ],
    teamRaiting: [
        {
            id: 1,
            img: require('@/mocks/team.png'),
            name: 'Команда пирожков',
            raitingValue: 5.0,
            ratingDay: 4,
            ratingWeek: 5,
            ratingMonth: 4,
        },
        {
            id: 2,
            img: require('@/mocks/team.png'),
            name: 'Команда пирожков',
            raitingValue: 5.0,
            ratingDay: 2,
            ratingWeek: 2,
            ratingMonth: 4,
        },
        {
            id: 3,
            img: require('@/mocks/team.png'),
            name: 'Команда пирожков',
            raitingValue: 5.0,
            ratingDay: 4,
            ratingWeek: 6,
            ratingMonth: 4,
        },
        {
            id: 4,
            img: require('@/mocks/team.png'),
            name: 'Команда пирожков',
            raitingValue: 5.0,
            ratingDay: 4,
            ratingWeek: 2,
            ratingMonth: 1,
        },
        {
            id: 5,
            img: require('@/mocks/team.png'),
            name: 'Команда пирожков',
            raitingValue: 5.0,
            ratingDay: 4,
            ratingWeek: 5,
            ratingMonth: 4,
        },
        {
            id: 6,
            img: require('@/mocks/team.png'),
            name: 'Команда пирожков',
            raitingValue: 5.0,
            ratingDay: 2,
            ratingWeek: 3,
            ratingMonth: 4,
        },
    ],
}

export default state
