export const COMPETITIONS_REQUEST_FETCHING = 'COMPETITIONS_REQUEST_FETCHING'
export const COMPETITIONS_REQUEST_SUCCESS = 'COMPETITIONS_REQUEST_SUCCESS'
export const COMPETITIONS_REQUEST_ERROR = 'COMPETITIONS_REQUEST_ERROR'
export const COMPETITIONS_REQUEST = 'COMPETITIONS_REQUEST'
