export const COMPETITION_REQUEST_FETCHING = 'COMPETITION_REQUEST_FETCHING'
export const COMPETITION_REQUEST_SUCCESS = 'COMPETITION_REQUEST_SUCCESS'
export const COMPETITION_REQUEST_ERROR = 'COMPETITION_REQUEST_ERROR'