export const WEEKLY_TASKS_REQUEST = 'WEEKLY_TASKS_REQUEST'
export const WEEKLY_TASKS_SUCCESS = 'WEEKLY_TASKS_SUCCESS'
export const WEEKLY_TASKS_ERROR = 'WEEKLY_TASKS_ERROR'

export const DAILY_TASKS_REQUEST = 'DAILY_TASKS_REQUEST'
export const DAILY_TASKS_SUCCESS = 'DAILY_TASKS_SUCCESS'
export const DAILY_TASKS_ERROR = 'DAILY_TASKS_ERROR'

export const MAIN_QUEST_REQUEST = 'MAIN_QUEST_REQUEST'
export const MAIN_QUEST_SUCCESS = 'MAIN_QUEST_SUCCESS'
export const MAIN_QUEST_ERROR = 'MAIN_QUEST_ERROR'
