export const TESTS_REQUEST = 'TESTS_REQUEST'
export const TESTS_REQUEST_SUCCESS = 'TESTS_REQUEST_SUCCESS'
export const TESTS_REQUEST_ERROR = 'TESTS_REQUEST_ERROR'

export const QUESTIONS_REQUEST = 'QUESTIONS_REQUEST'
export const QUESTIONS_REQUEST_SUCCESS = 'QUESTIONS_REQUEST_SUCCESS'
export const QUESTIONS_REQUEST_ERROR = 'QUESTIONS_REQUEST_ERROR'

export const SEND_ANSWERS_REQUEST = 'SEND_ANSWERS_REQUEST'
export const SEND_ANSWERS_REQUEST_SUCCESS = 'SEND_ANSWERS_REQUEST_SUCCESS'
export const SEND_ANSWERS_REQUEST_ERROR = 'SEND_ANSWERS_REQUEST_ERROR'
