export const USERS_REQUEST_FETCHING = 'USERS_REQUEST_FETCHING'
export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS'
export const USERS_REQUEST_ERROR = 'USERS_REQUEST_ERROR'
export const USERS_REQUEST = 'USERS_REQUEST'
